import { WasteDatabase, Mistplatz, Translations } from './types';

export const wasteDatabase: WasteDatabase = {
  "Clear Glass Bottle": { 
    emoji: "🍶", 
    icon: "GlassWater", 
    color: "blue", 
    bin: "White Glass Bin (Weißglas)", 
    category: "glass",
    instructions: "Empty and rinse bottles. Remove caps and lids, dispose of them in the Yellow Bin separately." 
  },
  "Colored Glass Bottle": { 
    emoji: "🍾", 
    icon: "GlassWater", 
    color: "blue", 
    bin: "Colored Glass Bin (Buntglas)", 
    category: "glass",
    instructions: "Empty and rinse bottles. Remove lids and dispose separately. Slightly tinted glass goes to Colored Glass too." 
  },
  "Glass Jar": { 
    emoji: "🥫", 
    icon: "Container", 
    color: "blue", 
    bin: "Glass Bin", 
    category: "glass",
    instructions: "Empty and rinse jars. Lids made of metal or plastic should go to the Yellow Bin." 
  },
  "Plastic Bottle": { 
    emoji: "🥤", 
    icon: "GlassWater", 
    color: "yellow", 
    bin: "Yellow Bin (Gelb)", 
    category: "plastic",
    instructions: "Empty, rinse, and flatten if possible to save bin space." 
  },
  "Tetra Pak": { 
    emoji: "🥛", 
    icon: "Box", 
    color: "yellow", 
    bin: "Yellow Bin (Gelb)", 
    category: "plastic",
    instructions: "Empty, rinse, and flatten. Composite beverage packages go into the Yellow Bin in Vienna." 
  },
  "Aluminum Can": { 
    emoji: "🥫", 
    icon: "Pipette", 
    color: "yellow", 
    bin: "Yellow Bin (Gelb)", 
    category: "plastic",
    instructions: "Empty and rinse. Metal beverage and food cans go to the Yellow Bin." 
  },
  "Plastic Container": { 
    emoji: "🥡", 
    icon: "Box", 
    color: "yellow", 
    bin: "Yellow Bin (Gelb)", 
    category: "plastic",
    instructions: "Empty and rinse empty yogurt pots, trays, containers. Clean packaging only!" 
  },
  "Newspaper": { 
    emoji: "📰", 
    icon: "Newspaper", 
    color: "green", 
    bin: "Paper Bin (Rot)", 
    category: "paper",
    instructions: "Clean and dry papers, magazines, envelopes, and advertising sheets." 
  },
  "Cardboard Box": { 
    emoji: "📦", 
    icon: "Box", 
    color: "green", 
    bin: "Paper Bin (Rot)", 
    category: "paper",
    instructions: "Flatten cardboard boxes before recycling to make space for others." 
  },
  "Office Paper": { 
    emoji: "📄", 
    icon: "FileText", 
    color: "green", 
    bin: "Paper Bin (Rot)", 
    category: "paper",
    instructions: "Clean office papers, books (without hardcovers), and writing pads." 
  },
  "Pizza Box": { 
    emoji: "🍕", 
    icon: "Pizza", 
    color: "green", 
    bin: "Paper Bin (Rot) / Restmüll", 
    category: "paper",
    instructions: "Clean and grease-free pizza boxes go in the paper bin. If heavily greasy with food remains, put in Restmüll (residual waste)." 
  },
  "Diaper": { 
    emoji: "👶", 
    icon: "Smile", 
    color: "gray", 
    bin: "Residual Waste (Restmüll)", 
    category: "residual",
    instructions: "Nappies/diapers belong in the Restmüll bin." 
  },
  "Broken Ceramic": { 
    emoji: "🍽️", 
    icon: "FlameKindling", 
    color: "gray", 
    bin: "Residual Waste (Restmüll)", 
    category: "residual",
    instructions: "Wrap broken ceramics in newspaper for safety first, then dispose in the Restmüll." 
  },
  "Cigarette Butt": { 
    emoji: "🚬", 
    icon: "FlameKindling", 
    color: "gray", 
    bin: "Residual Waste (Restmüll)", 
    category: "residual",
    instructions: "Ensure it is completely extinguished. Never throw glowing cigarettes into waste containers." 
  },
  "Food Scraps": { 
    emoji: "🍎", 
    icon: "Apple", 
    color: "purple", 
    bin: "Bio Bin (Braun)", 
    category: "bio",
    instructions: "Fruit scraps, tea bags, coffee grounds go in the Bio bin. No meat, bones, or dairy, please!" 
  },
  "Coffee Grounds": { 
    emoji: "☕", 
    icon: "Coffee", 
    color: "purple", 
    bin: "Bio Bin (Braun)", 
    category: "bio",
    instructions: "Coffee grounds and paper coffee filters are excellent for composting. Put them in the Bio Bin." 
  },
  "Garden Waste": { 
    emoji: "🌿", 
    icon: "Leaf", 
    color: "purple", 
    bin: "Bio Bin (Braun)", 
    category: "bio",
    instructions: "Leaves, grass cuttings, weeds, small branches, potting soil." 
  },
  "Battery": { 
    emoji: "🔋", 
    icon: "Battery", 
    color: "red", 
    bin: "Special Collection Point (Problemstoffe)", 
    category: "hazardous",
    instructions: "Batteries must never go into household bins! Take them to battery collection boxes in supermarket checkout counters or an MA48 location." 
  },
  "Paint": { 
    emoji: "🎨", 
    icon: "Palette", 
    color: "red", 
    bin: "Problemstoffsammelstelle (Hazardous Point)", 
    category: "hazardous",
    instructions: "Solvent-based paints, varnishes, chemicals must be submitted to the MA48 problem waste station." 
  },
  "Electronic Waste": { 
    emoji: "📱", 
    icon: "Smartphone", 
    color: "red", 
    bin: "Special Collection / MA48 Mistplatz", 
    category: "hazardous",
    instructions: "Old phones, chargers, laptops, small electronic appliances. Take them to an electronics dealer or an MA48 Mistplatz." 
  },
  "Furniture": { 
    emoji: "🪑", 
    icon: "UtilityPole", 
    color: "brown", 
    bin: "MA48 Mistplatz (Recycling Center)", 
    category: "bulky",
    instructions: "Tables, chairs, cupboards. Large bulky items can be brought to any MA48 Mistplatz recycling center free of charge." 
  },
  "Mattress": { 
    emoji: "🛏️", 
    icon: "Inbox", 
    color: "brown", 
    bin: "MA48 Mistplatz (Recycling Center)", 
    category: "bulky",
    instructions: "Mattress and carpets are processed as bulky waste. Dispose at your nearest MA48 Mistplatz." 
  },
  "Large Appliance": { 
    emoji: "🧰", 
    icon: "Wrench", 
    color: "brown", 
    bin: "MA48 Mistplatz (Recycling Center)", 
    category: "bulky",
    instructions: "Washing machines, fridges, ovens are classified as large electrical appliances. Bring them to the Mistplatz." 
  }
};

export const mistplaetze: Mistplatz[] = [
  { district: "10. Favoriten", name: "Favoriten", address: "Eva-Zilcher-Gasse 3" },
  { district: "11. Simmering", name: "Simmering", address: "Johann-Petrak-Gasse 1" },
  { district: "12. Meidling", name: "Hetzendorf", address: "Wundtgasse / Jägerhausgasse" },
  { district: "14. Penzing", name: "Auhof", address: "Wientalstraße 51" },
  { district: "16. Ottakring", name: "Ottakring", address: "Kendlerstraße 38a" },
  { district: "17. Hernals", name: "Hernals", address: "Richthausenstraße 2" },
  { district: "19. Döbling", name: "Heiligenstadt", address: "Grinzinger Straße 151" },
  { district: "21. Floridsdorf", name: "Stammersdorf", address: "Nikolsburger Gasse 12" },
  { district: "21. Floridsdorf", name: "Donaufeld", address: "Fultonstraße 10" },
  { district: "22. Donaustadt", name: "Stadlau", address: "Mühlwasserstraße 2" },
  { district: "22. Donaustadt", name: "Rinter (Rinterzelt)", address: "Percostraße 4" },
  { district: "23. Liesing", name: "Inzersdorf", address: "Südrandstraße 2" },
  { district: "23. Liesing", name: "Liesing", address: "Seybelgasse 7" }
];

export const translations: Translations = {
  en: {
    navProblem: "The Mess",
    navGuide: "Sorting Guide",
    navMap: "Bin Finder",
    navJoin: "Join Us!",
    navQuizzes: "Quizzes",
    quizSectionTitle: "Recycling",
    quizSectionSub: "Quizzes & Knowledge Checks",
    quizSectionDesc: "Challenge yourself with our fun, interactive quizzes to see if you are a true Viennese sorting expert! Perfect for citizens, families, and expats alike.",
    quiz1Title: "Yellow Bin Sorting Quiz",
    quiz1Desc: "Can you tell which packagings go together in Vienna's Yellow Bin (Gelbe Tonne)? Test your plastic and metal sorting skills.",
    quiz2Title: "Problem Waste & Hazardous Materials",
    quiz2Desc: "Batteries, toxic paints, or electronics: find out how to safely dispose of them and what belongs at a Mistplatz recycling hub.",
    quiz3Title: "The Ultimate Vienna Recycling Master",
    quiz3Desc: "The complete test! Prove your solid knowledge of Restmüll, Altpapier, Altglas, and Bio-Bins in Vienna.",
    quizStartBtn: "Take Quiz 📝",
    heroTitle: "Let's Recycle Right, Vienna!",
    heroSubTitle: "Sorting waste shouldn't feel like a surprise pop quiz in German class. Our fun guides make Vienna's recycling system easy to understand for everyone!",
    heroStartBtn: "Start Sorting",
    heroWhyBtn: "Why It Matters",
    whyTitle: "Why Vienna's Recycling Needs",
    whySubTitle: "Your Help",
    whyDesc: "Vienna's recycling system is highly efficient, but language barriers and complex municipal rules mean wrong sorting happens often. We make it easy!",
    probComplexTitle: "Complex Sorting Rules",
    probComplexDesc: "Different materials go in different bins, and some items require physical travel to special collection points.",
    probLanguageTitle: "Language Barriers",
    probLanguageDesc: "Most instructional stickers on bins are strictly in German, creating massive confusion for international residents.",
    probMapTitle: "Bin Locations & Centers",
    probMapDesc: "Finding the appropriate bins for glass or hazardous materials requires knowing where you are and municipal districts.",
    superTitle: "Our Friendly",
    superSubTitle: "Superpower?",
    superDesc: "We decode confusing Austrian disposal laws and provide clear visual, multilingual guides. Just search any waste term below!",
    superEnTitle: "English",
    superEnDesc: "Clear and straightforward instructions for Vienna's massive international community.",
    superRuTitle: "Russian",
    superRuDesc: "Simplified Russian waste-sorting instructions and bin specifications.",
    superTrTitle: "Turkish",
    superTrDesc: "Tailored translations and helpful hints for Vienna's Turkish speaking citizens.",
    visualTitle: "Immersive Visuals",
    visualDesc: "We pair lovely color codings and distinctive flat layouts to skip learning hurdles completely. Colors map perfectly to Vienna's real bin lids!",
    guideTitle: "Your Easy",
    guideSubTitle: "Sorting Guide",
    guideDesc: "Wondering where a waste item belongs? Type it in below or choose a category button!",
    searchPlaceholder: "What do you want to recycle? e.g., Pizza box, old batteries, mattress...",
    searchDisclaimer: "Note: This sorting tool is currently in development and not fully optimized yet. We are working hard to expand its database!",
    searchBtn: "Sort It!",
    catGlass: "Glass",
    catGlassSub: "Bottles & Jars",
    catPlastic: "Packaging",
    catPlasticSub: "Plastic & Metal",
    catPaper: "Paper",
    catPaperSub: "Clean & Dry",
    catResidual: "Residual",
    catResidualSub: "Non-Recyclable",
    catBio: "Bio",
    catBioSub: "Food & Garden",
    catHazardous: "Hazardous",
    catHazardousSub: "Problem Substances",
    catBulky: "Bulky",
    catBulkySub: "Large items / Furniture",
    downloadTitle: "Download Full Waste Guide",
    downloadSub: "Available in English, and other languages will be available in the future 🎨",
    downloadBtnEn: "English Guide",
    downloadBtnRu: "Russian Guide",
    downloadBtnTr: "Turkish Guide",
    downloadBtnDe: "German Guide",
    faqTitle: "Burning",
    faqSub: "Recycling Questions",
    faqDesc: "Get simple answers to the most mind-boggling sorting dilemmas in Vienna.",
    mapTitle: "Find Your Nearest",
    mapSub: "Recycling Bins",
    mapDesc: "Locate primary waste centers (Mistplätze) operated by the municipal department MA48 in Vienna.",
    tblDistrict: "District (Bezirk)",
    tblName: "Collection Center Name",
    tblAddress: "Address (Adresse)",
    socialTitle: "Follow Our",
    socialSub: "Recycling Adventures",
    socialDesc: "We make municipal waste sorting entertaining and fun on social media! (Yes, really!)",
    socialInstDesc: "Daily recycling tips, bin coloring sheets, and local fun facts in Vienna @viennarecycling.",
    socialFbDesc: "Connect with fellow citizens, see event alerts, and get news on Facebook @viennarecycling.",
    socialProjDesc: "Learn more about our educational mission to make recycling simple for expats in Vienna.",
    communityTitle: "Join Our",
    communitySub: "Recycling Community",
    communityDesc: "Get our charming newsletter with sorting games, local volunteer updates, and ecology tips.",
    emailPlaceholder: "Enter your email address...",
    subscribeBtn: "Subscribe",
    pvtSubscribeSuccess: "Thank you for joining our community! 💚 Check your inbox for our waste classification game soon.",
    projAboutTitle: "About the Compass Project",
    projAboutSub: "Making Recycling Simple for Expats",
    projAboutDesc: "The Vienna Recycling Compass is an educational initiative supported by the European Solidarity Corps and designed in partnership with EUActive. Our mission is to dismantle language and cultural barriers in municipal waste management, helping newcomers, expats, and locals alike navigate Vienna's complex recycling rules with ease, beautiful visual tools, and interactive quizzes.",
    projAboutBadge: "European Solidarity Initiative",
    projAboutBtn: "Official Project Page",
    footerAbout: "Vienna Recycling Compass",
    footerSlogan: "Making Vienna cleaner, together",
    footerAboutDesc: "A user-friendly, community-driven guide simplifying waste sorting under the Vienna City Council and MA48 frameworks.",
    footerStayUpdated: "Stay Updated",
    footerLinks: "Quick Links",
    footerResources: "Resources",
    footerCookie: "Cookie Policy",
    footerPrivacy: "Privacy Policy",
    footerTerms: "Terms of Service"
  },
  de: {
    navProblem: "Das Problem",
    navGuide: "Müll-Guide",
    navMap: "Mistplatz-Finder",
    navJoin: "Mitmachen!",
    navQuizzes: "Rätsel / Quizzes",
    quizSectionTitle: "Mülltrennung",
    quizSectionSub: "Quizzes & Wissenstests",
    quizSectionDesc: "Fordere dich selbst mit unseren unterhaltsamen, interaktiven Quizzes heraus, um zu sehen, ob du ein echter Wiener Trenn-Profi bist! Perfekt für Bürger, Familien und Expats.",
    quiz1Title: "Gelbe Tonne Sortier-Quiz",
    quiz1Desc: "Weißt du genau, welche Verpackungen in die Gelbe Tonne gehören? Teste dein Wissen über Plastik und Metall.",
    quiz2Title: "Problemstoffe & Gefährlicher Abfall",
    quiz2Desc: "Batterien, giftige Farben oder Elektrogeräte: Finde heraus, wie man sie sicher entsorgt und was auf den Mistplatz gehört.",
    quiz3Title: "Der Ultimative Wiener Müllmeister",
    quiz3Desc: "Der komplette Test! Beweise dein solides Wissen über Restmüll, Altpapier, Altglas und die Biotonne in Wien.",
    quizStartBtn: "Quiz starten 📝",
    heroTitle: "Müll trennen leicht gemacht, Wien!",
    heroSubTitle: "Das Sortieren von Abfällen sollte sich nicht wie ein unangekündigter Vokabeltest anfühlen. Unsere humorvollen Anleitungen machen Wiens Recyclingsystem für jeden verständlich!",
    heroStartBtn: "Jetzt Trennen",
    heroWhyBtn: "Warum es zählt",
    whyTitle: "Warum Wiens Mülltrennung",
    whySubTitle: "Deine Hilfe braucht",
    whyDesc: "Wiens Entsorgungssystem ist hochmodern, aber Sprachbarrieren und komplexe Regeln führen oft zu Fehlern beim Sortieren. Wir ändern das!",
    probComplexTitle: "Komplexe Regeln",
    probComplexDesc: "Unterschiedliche Materialien gehören in trennende Tonnen, und einige erfordern sogar den Weg zu Recyclinghöfen.",
    probLanguageTitle: "Sprachbarrieren",
    probLanguageDesc: "Anleitungen auf den Containern sind meist ausschließlich auf Deutsch, was für internationale Wiener verwirrend ist.",
    probMapTitle: "Container-Standorte",
    probMapDesc: "Das Finden der richtigen Tonne für Altglas oder Sondermüll erfordert oft langes Suchen im jeweiligen Bezirk.",
    superTitle: "Unsere kleine",
    superSubTitle: "Superkraft?",
    superDesc: "Wir entschlüsseln Wiener Entsorgungsgesetze in einfache visuelle, mehrsprachige Anleitungen. Such einfach unten deinen Müll!",
    superEnTitle: "Englisch",
    superEnDesc: "Klare, verständliche Anleitungen für Wiens internationale Gemeinschaft.",
    superRuTitle: "Russisch",
    superRuDesc: "Vereinfachte russische Sortieranleitungen und Behälterspezifikationen.",
    superTrTitle: "Türkisch",
    superTrDesc: "Maßgeschneiderte Übersetzungen und Mülltupfen für türkischsprachige Wiener.",
    visualTitle: "Visualisierungen",
    visualDesc: "Wir nutzen ansprechende Farbcodes, die perfekt zu den realen Deckeln der Wiener Mülltonnen (Gelb, Rot, Braun) passen!",
    guideTitle: "Dein einfacher",
    guideSubTitle: "Müll-Guide",
    guideDesc: "Suchst du den richtigen Ort für einen Gegenstand? Tippe ihn ein oder wähle eine Kategorie!",
    searchPlaceholder: "Was möchtest du entsorgen? z.B. Pizzakarton, alte Batterien, Matratze...",
    searchDisclaimer: "Hinweis: Dieses Sortierungs-Tool befindet sich noch in der Entwicklung und ist nicht vollständig optimiert. Wir arbeiten hart daran, die Produktdatenbank zu erweitern!",
    searchBtn: "Sortieren!",
    catGlass: "Altglas",
    catGlassSub: "Flaschen & Gläser",
    catPlastic: "Verpackungen",
    catPlasticSub: "Plastik & Metall",
    catPaper: "Altpapier",
    catPaperSub: "Sauber & Trocken",
    catResidual: "Restmüll",
    catResidualSub: "Nicht recyclebar",
    catBio: "Biomüll",
    catBioSub: "Nahrung & Garten",
    catHazardous: "Problemstoffe",
    catHazardousSub: "Gefährliche Abfälle",
    catBulky: "Sperrmüll",
    catBulkySub: "Möbel & Große Dinge",
    downloadTitle: "Vollen Müll-Guide herunterladen",
    downloadSub: "Auf Englisch verfügbar, weitere Sprachen folgen in Kürze 🎨",
    downloadBtnEn: "Englischer Guide",
    downloadBtnRu: "Russischer Guide",
    downloadBtnTr: "Türkischer Guide",
    downloadBtnDe: "Deutscher Guide",
    faqTitle: "Brennende",
    faqSub: "Müll-Fragen",
    faqDesc: "Hier findest du einfache Antworten auf die verwirrendsten Recycling-Rätsel Wiens.",
    mapTitle: "Finde deinen nächsten",
    mapSub: "Mistplatz im Bezirk",
    mapDesc: "Finde Recyclinghöfe der Wiener Müllabfuhr (Sammelstellen der Magistratsabteilung MA48) in Wien.",
    tblDistrict: "Bezirk",
    tblName: "Mistplatz / Name",
    tblAddress: "Adresse",
    socialTitle: "Folge unseren",
    socialSub: "Müll-Abenteuern",
    socialDesc: "Wir machen Mülltrennung auf Social Media unterhaltsam und lehrreich! (Ja, wirklich!)",
    socialInstDesc: "Tägliche Trenntipps, lustige Grafiken und lokale Wiener Müllfakten auf Instagram @viennarecycling.",
    socialFbDesc: "Vernetze dich mit anderen, erfahre von Terminen und MA48-Infos auf Facebook @viennarecycling.",
    socialProjDesc: "Erfahre mehr über unser Bildungsprojekt, das die Mülltrennung für Expats in Wien erleichtert.",
    communityTitle: "Werde Teil der",
    communitySub: "Community",
    communityDesc: "Melde dich für unseren charmanten Newsletter an mit Müll-Spielen, lokalen Treffen und Öko-Tipps.",
    emailPlaceholder: "Deine E-Mail-Adresse...",
    subscribeBtn: "Abonnieren",
    pvtSubscribeSuccess: "Danke für deine Anmeldung! 💚 Du erhältst in Kürze unser Müll-Klassifikationsspiel per Mail.",
    projAboutTitle: "Über das Compass-Projekt",
    projAboutSub: "Mülltrennung für Expats leicht gemacht",
    projAboutDesc: "Der Vienna Recycling Compass ist eine Bildungsinitiative, die vom Europäischen Solidaritätskorps unterstützt und in Partnerschaft mit EUActive entwickelt wurde. Unsere Mission ist es, sprachliche und kulturelle Barrieren in der städtischen Abfallwirtschaft abzubauen, um Neuankömmlingen, Expats und Einheimischen zu helfen, Wiens komplexe Recyclingregeln mit interaktiven Quizzes und ansprechenden visuellen Werkzeugen spielend leicht zu meistern.",
    projAboutBadge: "Europäische Solidaritätsinitiative",
    projAboutBtn: "Offizielle Projektseite",
    footerAbout: "Vienna Recycling Compass",
    footerSlogan: "Gemeinsam für ein saubereres Wien",
    footerAboutDesc: "Ein benutzerfreundlicher,社区-gesteuerter Leitfaden, der die Mülltrennung im Rahmen des Wiener Magistrats und der MA48 erleichtert.",
    footerStayUpdated: "Updates erhalten",
    footerLinks: "Schnelllinks",
    footerResources: "Ressourcen",
    footerCookie: "Cookie-Richtlinie",
    footerPrivacy: "Datenschutz",
    footerTerms: "Nutzungsbedingungen"
  },
  ru: {
    navProblem: "Проблема",
    navGuide: "Сортировка",
    navMap: "Карта Mistplatz",
    navJoin: "Сообщество",
    navQuizzes: "Викторины",
    quizSectionTitle: "Раздельный Сбор",
    quizSectionSub: "Тесты на знание ресайклинга",
    quizSectionDesc: "Проверьте себя в наших веселых интерактивных викторинах! Узнайте, насколько хорошо вы разбираетесь в тонкостях раздельного сбора мусора в Вене.",
    quiz1Title: "Викторина: Желтый контейнер",
    quiz1Desc: "Разберитесь до конца, какие виды пластика и металла отправляются в Gelbe Tonne в Вене.",
    quiz2Title: "Опасные отходы и Проблемные вещества",
    quiz2Desc: "Батарейки, остатки краски или электроника: проверьте, как правильно их утилизировать через центры MA48.",
    quiz3Title: "Ультимативный Мастер Сортировки",
    quiz3Desc: "Финальный босс! Главный тест на знание предназначения Restmüll, Papier, Altglas и Bio-урн.",
    quizStartBtn: "Пройти тест 📝",
    heroTitle: "Сортируем правильно, Вена!",
    heroSubTitle: "Разделение мусора не должно напоминать внезапный тест по немецкому языку. Наши веселые карточки помогут разобраться в экосиней, желтой и красной урнах Вены за пару минут!",
    heroStartBtn: "Начать сортировку",
    heroWhyBtn: "Почему это важно",
    whyTitle: "Почему венианскому ресайклингу",
    whySubTitle: "Нужна твоя помощь",
    whyDesc: "Венская городская служба работает великолепно, но языковые барьеры и уникальные правила сортировки часто ведут к ошибкам. Мы делаем сортировку интуитивной!",
    probComplexTitle: "Сложные правила",
    probComplexDesc: "Разные материалы идут в строго определенные контейнеры, а опасный мусор нужно самостоятельно везти на пункты MA48.",
    probLanguageTitle: "Языковой барьер",
    probLanguageDesc: "Все надписи на мусорных баках в Вене нанесены на немецком языке, создавая путаницу для иностранных жителей.",
    probMapTitle: "Поиск баков и центров",
    probMapDesc: "Порой сложно найти контейнер для цветного стекла или сдать старый аккумулятор в своем районе без подробных карт.",
    superTitle: "Наша скромная",
    superSubTitle: "Суперсила?",
    superDesc: "Мы перевели запутанные австрийские правила в простые визуальные карточки на разных языках. Просто введи название вещи в поиск!",
    superEnTitle: "Английский",
    superEnDesc: "Простые инструкции и переводы для многочисленного международного сообщества Вены.",
    superRuTitle: "Русский",
    superRuDesc: "Адаптированные инструкции по сортировке отходов на русском языке.",
    superTrTitle: "Турецкий",
    superTrDesc: "Интуитивный перевод правил сортировки мусора для турецкоязычных жителей.",
    visualTitle: "Простые иллюстрации",
    visualDesc: "Мы привязали цвета карточек к реальным мусорным крышкам баков в Вене (желтый, красный, био, бумага), чтобы вы вообще не тратили время на чтение!",
    guideTitle: "Твой удобный",
    guideSubTitle: "Мусорный советник",
    guideDesc: "Не знаешь куда выбросить какую-то вещь? Напиши в строке поиска или выбери категорию!",
    searchPlaceholder: "Что вы хотите утилизировать? Например, коробка от пиццы, батарейки, матрас...",
    searchDisclaimer: "Примечание: Этот инструмент поиска находится в процессе активной разработки и ещё не полностью оптимизирован. Мы активно работаем над расширением базы данных!",
    searchBtn: "Сортировать!",
    catGlass: "Альтглас",
    catGlassSub: "Бутылки и банки",
    catPlastic: "Упаковка",
    catPlasticSub: "Пластик и металл",
    catPaper: "Бумага",
    catPaperSub: "Чистая и сухая",
    catResidual: "Смешанный мусор",
    catResidualSub: "Остаточные отходы",
    catBio: "Био-отходы",
    catBioSub: "Еда и органика",
    catHazardous: "Опасные отходы",
    catHazardousSub: "Проблемные вещества",
    catBulky: "Крупногабаритный",
    catBulkySub: "Мебель и техника",
    downloadTitle: "Скачать полный гид по мусору",
    downloadSub: "Доступно на английском языке, другие языки будут добавлены в будущем 🎨",
    downloadBtnEn: "Гид на английском",
    downloadBtnRu: "Гид на русском",
    downloadBtnTr: "Гид на турецком",
    downloadBtnDe: "Гид на немецком",
    faqTitle: "Актуальные",
    faqSub: "Мусорные вопросы",
    faqDesc: "Понятные и четкие ответы на самые частые загадки сортировки в австрийской столице.",
    mapTitle: "Карта центров утилизации",
    mapSub: "MA48 Mistplatz",
    mapDesc: "Найдите адреса крупных районных сортировочных центров Mistplatz в Вене.",
    tblDistrict: "Район (Bezirk)",
    tblName: "Название площадки",
    tblAddress: "Адрес",
    socialTitle: "Наши",
    socialSub: "Эко-приключения",
    socialDesc: "Мы делаем раздельный сбор мусора модным и забавным в социальных сетях! (Да-да, это реальный фан!)",
    socialInstDesc: "Полезные карточки, экологические факты о Вене в Instagram @viennarecycling.",
    socialFbDesc: "Общайтесь с единомышленниками, узнавайте о мероприятиях в Facebook @viennarecycling.",
    socialProjDesc: "Узнайте больше о нашей образовательной миссии по упрощению сортировки мусора для экспатов в Вене.",
    communityTitle: "Вступай в",
    communitySub: "Зеленое сообщество",
    communityDesc: "Присоединяйся к рассылке: делимся играми для детей, новостями эко-прогулок и субботников в Вене.",
    emailPlaceholder: "Твой адрес почты...",
    subscribeBtn: "Подписаться",
    pvtSubscribeSuccess: "Спасибо за подписку! 💚 Накануне субботников пришлем вам ссылку на онлайн-игру по сортировке.",
    projAboutTitle: "О проекте Compass",
    projAboutSub: "Простая сортировка для экспатов",
    projAboutDesc: "Венский компас ресайклинга — это образовательная инициатива, поддерживаемая Европейским корпусом солидарности и разработанная в партнерстве с EUActive. Наша цель — устранить языковые и культурные барьеры в сфере городских отходов, помогая экспатам, студентам и всем жителям Вены легко осваивать правила сортировки с помощью интерактивных тестов и наглядных визуальных материалов.",
    projAboutBadge: "Европейская инициатива солидарности",
    projAboutBtn: "Официальная страница",
    footerAbout: "Vienna Recycling Compass",
    footerSlogan: "Сделаем Вену чище вместе",
    footerAboutDesc: "Простой и понятный путеводитель для облегчения раздельного сбора отходов, созданный с уважением к правилам магистрата Вены и MA48.",
    footerStayUpdated: "Будь в курсе",
    footerLinks: "Быстрые ссылки",
    footerResources: "Ресурсы",
    footerCookie: "Политика Cookie",
    footerPrivacy: "Конфиденциальность",
    footerTerms: "Условия использования"
  },
  tr: {
    navProblem: "Zorluklar",
    navGuide: "Rehber",
    navMap: "Atık Merkezi Bulucu",
    navJoin: "Topluluk",
    navQuizzes: "Testler",
    quizSectionTitle: "Geri Dönüşüm",
    quizSectionSub: "Eğlenceli Bilgi Testleri",
    quizSectionDesc: "Viyana'da gerçek bir geri dönüşüm uzmanı olup olmadığınızı görmek için kendinizi eğlenceli ve interaktif testlerimizle deneyin!",
    quiz1Title: "Sarı Kutu (Gelbe Tonne) Sınıflandırma Testi",
    quiz1Desc: "Viyana'daki Sarı Kutuya hangi ambalajların gireceğini biliyor musunuz? Plastik ve metal ayırma becerilerinizi test edin.",
    quiz2Title: "Tehlikeli Maddeler ve Problemstoff",
    quiz2Desc: "Piller, zararlı boyalar veya elektronik atıklar: Bunları güvenli bir şekilde nasıl bertaraf edeceğinizi öğrenin.",
    quiz3Title: "Viyana Geri Dönüşüm Ustası",
    quiz3Desc: "En kapsamlı test! Restmüll, Altpapier, Altglas ve Bio-çöp kutuları hakkındaki bilgilerinizi kanıtlayın.",
    quizStartBtn: "Teste Başla 📝",
    heroTitle: "Hadi Doğru Geri Dönüştürelim, Viyana!",
    heroSubTitle: "Çöp ayıklamak, Almanca dersindeki habersiz yazılı sınav gibi hissettirmemeli. Eğlenceli kılavuzlarımız Viyana'nın geri dönüşüm sistemini herkes için kolaylaştırıyor!",
    heroStartBtn: "Ayıklamaya Başla",
    heroWhyBtn: "Neden Önemli?",
    whyTitle: "Viyana'nın Geri Dönüşümü",
    whySubTitle: "Yardımınızı Bekliyor",
    whyDesc: "Viyana'nın atık yönetim sistemi son derece gelişmiştir, ancak dil engelleri ve karmaşık kurallar nedeniyle çöpler sıklıkla yanlış kutulara gitmektedir. Biz bunu çözüyoruz!",
    probComplexTitle: "Karmaşık Kurallar",
    probComplexDesc: "Farklı malzemeler ayrı kutulara girer, piller ve tehlikeli maddeler için özel toplama noktalarına taşınması gerekir.",
    probLanguageTitle: "Dil Engelleri",
    probLanguageDesc: "Çöp kutularındaki bilgilendirme etiketleri genellikle sadece Almancadır, bu durum uluslararası sakinler için kafa karıştırıcıdır.",
    probMapTitle: "Kutu ve Mistplatz Konumları",
    probMapDesc: "Cam toplama kaplarını ve tehlikeli atık bertaraf noktalarını semtinizde bulmak bazen karmaşık bir hal alabilir.",
    superTitle: "Bizim Sevimli",
    superSubTitle: "Süper Gücümüz?",
    superDesc: "Karmaşık Avusturya geri dönüşüm mevzuatını basit görsel ve çok dilli rehberlere dönüştürüyoruz. Sadece çöpünüzü aratın!",
    superEnTitle: "İngilizce",
    superEnDesc: "Viyana'nın kalabalık uluslararası topluluğu için net ve anlaşılır talimatlar.",
    superRuTitle: "Rusça",
    superRuDesc: "Rusça konuşan sakinler için basitleştirilmiş atık ayırma talimatları.",
    superTrTitle: "Türkçe",
    superTrDesc: "Türkçe konuşan Viyana sakinleri için özel olarak çevrilmiş çevre yönergeleri.",
    visualTitle: "Eğlenceli Görseller",
    visualDesc: "Açıklayıcı renk kodlarımız Viyana'daki gerçek çöp konteyneri kapaklarıyla (Sarı, Kırmızı, Kahverengi) birebir örtüşür, böylece okumadan anlarsınız!",
    guideTitle: "Senin Kolay",
    guideSubTitle: "Müll Rehberin",
    guideDesc: "Hangi çöpün nereye atılacağını mı merak ediyorsunuz? Arama çubuğuna yazın veya bir kategori butonuna dokunun!",
    searchPlaceholder: "Neyi geri dönüştürmek istiyorsunuz? örn. Pizza kutusu, piller, matras...",
    searchDisclaimer: "Not: Bu arama ve sınıflandırma aracı henüz geliştirme aşamasındadır ve tam olarak optimize edilmemiştir. Atık veri tabanımızı genişletmek için yoğun bir şekilde çalışıyoruz!",
    searchBtn: "Yönlendir!",
    catGlass: "Cam Atık",
    catGlassSub: "Şişeler & Kavanozlar",
    catPlastic: "Ambalajlar",
    catPlasticSub: "Plastik & Metal",
    catPaper: "Kağıt Atık",
    catPaperSub: "Temiz & Kuru",
    catResidual: "Evsel Atık",
    catResidualSub: "Dönüştürülemeyen",
    catBio: "Biyolojik Atık",
    catBioSub: "Yiyecek & Bahçe",
    catHazardous: "Zararlı Atık",
    catHazardousSub: "Tehlikeli Maddeler",
    catBulky: "Kaba Çöp",
    catBulkySub: "Hacimli Mobilyalar",
    downloadTitle: "Tüm Çöp Klavuzunu İndir",
    downloadSub: "İngilizce olarak mevcuttur, diğer diller gelecekte eklenecektir 🎨",
    downloadBtnEn: "İngilizce Kılavuz",
    downloadBtnRu: "Rusça Kılavuz",
    downloadBtnTr: "Türkçe Kılavuz",
    downloadBtnDe: "Almanca Kılavuz",
    faqTitle: "Sorulan",
    faqSub: "Geri Dönüşüm Soruları",
    faqDesc: "Avusturya başkentindeki atık yönetimi konusunda en sık kafa kurcalayan soruların yanıtları burada.",
    mapTitle: "En Yakın Atık Merkezleri",
    mapSub: "MA48 Mistplatz",
    mapDesc: "Viyana belediyesi MA48 tarafından işletilen Mistplatz geri dönüşüm tesislerini haritada bulun.",
    tblDistrict: "Semt (Bezirk)",
    tblName: "Geri Dönüşüm İstasyonu",
    tblAddress: "Adres (Adresse)",
    socialTitle: "Bizi Sosyal Medyada",
    socialSub: "Takip Edin",
    socialDesc: "Sosyal medyada atık ayırmayı eğlenceli ve popüler kılmaya çalışıyoruz! (Ciddiyiz, çok keyifli!)",
    socialInstDesc: "Instagram sayfamızda günlük ipuçları ve renkli grafikler @viennarecycling.",
    socialFbDesc: "Facebook grubumuzda diğer vatandaşlarla bağlantı kurun ve etkinlikleri takip edin @viennarecycling.",
    socialProjDesc: "Viyana'daki yabancılar için geri dönüşümü kolaylaştırmaya yönelik eğitim misyonumuz hakkında daha fazla bilgi edinin.",
    communityTitle: "Çevre Dostu",
    communitySub: "Topluluğumuza Katılın",
    communityDesc: "Geri dönüşüm oyunları, yerel buluşmalar ve pratik yeşil yaşam tüyoları içeren bültenimize abone olun.",
    emailPlaceholder: "E-posta adresiniz...",
    subscribeBtn: "Abone Ol",
    pvtSubscribeSuccess: "Aboneliğiniz için teşekkürler! 💚 Kısa süre içinde çöp ayırma oyunumuzun linkini mail kutunuzda bulacaksınız.",
    projAboutTitle: "Compass Projesi Hakkında",
    projAboutSub: "Gurbetçiler İçin Kolay Geri Dönüşüm",
    projAboutDesc: "Viyana Geri Dönüşüm Pusulası (Vienna Recycling Compass), Avrupa Dayanışma Programı tarafından desteklenen ve EUActive ortaklığıyla tasarlanan eğitici bir girişimdir. Misyonumuz, belediye atık yönetimindeki dil ve kültür engellerini ortadan kaldırarak; Viyana'ya yeni gelenlerin, göçmenlerin ve yerel halkın karmaşık geri dönüşüm kurallarını etkileşimli testler ve harika görsel araçlarla kolayca öğrenmesini sağlamaktır.",
    projAboutBadge: "Avrupa Dayanışma Girişimi",
    projAboutBtn: "Resmi Proje Sayfası",
    footerAbout: "Vienna Recycling Compass",
    footerSlogan: "Viyana'yı birlikte daha temiz tutalım",
    footerAboutDesc: "Viyana Belediyesi ve MA48 direktifleri doğrultusunda geri dönüşümü eğlenceli hale getiren kullanıcı odaklı bağımsız bir rehber.",
    footerStayUpdated: "Haberdar Kalın",
    footerLinks: "Pratik Linkler",
    footerResources: "Kaynaklar",
    footerCookie: "Çerez Politikası",
    footerPrivacy: "Gizlilik Politikası",
    footerTerms: "Kullanım Şartları"
  }
};

export const faqsList: { [lang: string]: Array<{ q: string; a: string }> } = {
  en: [
    {
      q: "What goes in the yellow bin (Gelbe Tonne)?",
      a: "The Yellow Bin in Vienna holds lightweight plastic packages (like bottles and pots), metal packagings (like aluminum drink cans), and composite packagings (like beverage cartons / Tetra Paks)."
    },
    {
      q: "How should I sort glass?",
      a: "Always separate colored and clear glass. Transparent glass jars and bottles go in the White Glass (Weißglas) bin. Even slightly colored, frosted, or brown glass belongs inside the Colored Glass (Buntglas) bin. Be sure to strip lids!"
    },
    {
      q: "Are pizza boxes recyclable?",
      a: "If the pizza box is clean, dry, and has no grease puddles or cheese residue, put it in the Paper Bin. If it is heavily stained with oil, food scraps, or wax coatings, dispose of it in the Residual Waste (Restmüll) so it won't contaminate paper batches."
    },
    {
      q: "What are the rules for bio waste (Biotonne)?",
      a: "Perfect for fruit/veg scraps, plant clippings, and tea/coffee grounds with their paper bags. NEVER put plastic bags, diapers, metal, pet droppings, bones, meat, fish, or dairy in the Biomüll."
    },
    {
      q: "Where do used household batteries belong?",
      a: "Never throw batteries in any home bin! This can trigger warehouse fires. Return old batteries directly into collection boxes found at most grocery grocery store checkouts, or pack them to an MA48 collection point."
    },
    {
      q: "How to dispose of electronics, chargers, & appliances?",
      a: "Do not throw electronics in the Restmüll. Any small gadget or wire can be delivered to electrical outlets (over 150sqm size) free or brought directly to your neighborhood MA48 Mistplatz."
    }
  ],
  de: [
    {
      q: "Was kommt in die Gelbe Tonne?",
      a: "In Wien kommen alle Leichtverpackungen aus Kunststoff (Flaschen, Becher), Metallverpackungen (Aludosen, Flaschenverschlüsse) sowie Verbundstoff-Getränkekartons (Tetra Paks) in die Gelbe Tonne."
    },
    {
      q: "Wie sortiert man Altglas richtig?",
      a: "Trennen Sie nach Weißglas (vollkommen transparent) und Buntglas (gefärbt, braun, grün oder mattiert). Metallverschlüsse gehören in die feine Gelbe Tonne."
    },
    {
      q: "Dürfen Pizzakartons ins Altpapier?",
      a: "Nur saubere, unbeschichtete und fettfreie Kartons gehören ins Altpapier. Stark verschmutzte oder fettige Kartons mit Essensresten gehören unbedingt in den Restmüll."
    },
    {
      q: "Welche Regeln gelten für die Biotonne?",
      a: "Geeignet für Obst- und Gemüsereste, Kaffeesatz, Teeblätter und Gartenabfälle. Speisereste wie Fleisch, Fisch, Knochen oder Milchprodukte gehören hingegen in den Restmüll."
    },
    {
      q: "Wohin gehören leere Batterien?",
      a: "Niemals in den Hausmüll werfen! Sie enthalten wertvolle Rohstoffe, aber auch Giftstoffe. Abgeben können Sie Batterien in jedem Supermarkt an der Kassa oder am Mistplatz."
    },
    {
      q: "Wie entsorgt man kaputte Elektrogeräte?",
      a: "Kleine Elektrogeräte wie Handys oder Ladekabel können gratis in großen Geschäften abgegeben werden oder zu einem der MA48 Mistplätze gebracht werden."
    }
  ],
  ru: [
    {
      q: "Что выбрасывают в желтый бак (Gelbe Tonne)?",
      a: "В желтый бак складывают пластиковую упаковку (бутылки, стаканчики от йогуртов), металлическую упаковку (жестяные баночки) и комбинированную упаковку (коробки Tetra Pak)."
    },
    {
      q: "Как правильно сортировать стекло?",
      a: "Стекло сортируется по цвету: бесцветное стекло идет в бак Weißglas, а цветное (зеленое, коричневое, полуматовое) — в Buntglas."
    },
    {
      q: "Можно ли выбрасывать коробку от пиццы в макулатуру?",
      a: "Если коробка чистая и сухая, без следов жира и сыра, кладите в бак для бумаги. Если коробка сильно запятнана маслом, ее место в Restmüll."
    },
    {
      q: "Каковы правила для био-контейнеров (Biotonne)?",
      a: "Туда подходят остатки фруктов и овощей, кофейная гуща, чайные пакетики и садовые сорняки. Мясо, рыба, кости и молочные продукты выбрасывать туда нельзя."
    },
    {
      q: "Куда девать старые батарейки?",
      a: "Ни в коем случае не бросайте их в домашний мусор! Сдавайте батарейки в специальные коробки у касс в супермаркетах или отвозите на Mistplatz."
    },
    {
      q: "Как утилизировать электронику и зарядные устройства?",
      a: "Любые сетевые провода, зарядки и гаджеты нельзя бросать вRestmüll. Их бесплатно принимают крупные магазины электроники или любые пункты MA48 Mistplatz."
    }
  ],
  tr: [
    {
      q: "Sarı çöp kutusuna (Gelbe Tonne) neler atılır?",
      a: "Viyana'da sarı kutu her türlü hafif plastik ambalaj (şişeler, kaplar), metal kutular (alüminyum içecek kutuları) ve kompozit içecek kartonları (Tetra Pak) için kullanılır."
    },
    {
      q: "Altglas (Cam Atık) nasıl ayrıştırılır?",
      a: "Renkli ve renksiz camları her zaman ayırın. Berrak cam şişe ve kavanozlar Weißglas kutusuna atılır. Hafif renkli veya kahverengi camlar ise Buntglas kutusuna gider."
    },
    {
      q: "Pizza kutuları geri dönüştürülebilir mi?",
      a: "Pizza kutusu temiz ve yağsız ise Kağıt Kutusuna (Papiertonne) atılabilir. Yoğun yağ lekesi veya yiyecek artığı varsa kesinlikle Restmüll kutusuna atılmalıdır."
    },
    {
      q: "Organik atık kutusunun (Biotonne) kuralları nelerdir?",
      a: "Meyve/sebze artıkları, çay/kahve telveleri ve bahçe otları için uygundur. Et, kemik, balık, süt ürünleri veya plastik torbalar ise kesinlikle atılmamalıdır."
    },
    {
      q: "Kullanılmış ev pilleri nereye atılmalıdır?",
      a: "Piller asla evdeki normal çöpe atılmamalıdır! Yangın riski taşırlar. Süpermarket kasalarındaki toplama kutularına veya MA48 noktalarına bırakabilirsiniz."
    },
    {
      q: "Elektronik eşyalar ve şarj cihazları nasıl atılmalıdır?",
      a: "Kör kablolar ve eski elektronik aletler Restmüll'e atılmaz. Bunları ücretsiz olarak büyük elektronik mağazalarına verebilir veya mahalledeki MA48 Mistplatz merkezine götürebilirsiniz."
    }
  ]
};
